services:
    memcached:
        image: 'memcached:alpine'

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '.:/application'
            - './nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8000:80'
        depends_on:
            - php-fpm

    php-fpm:
        build: .
        working_dir: /application
        volumes:
            - '.:/application'
            - './php-ini-overrides.ini:/etc/php/8.3/fpm/conf.d/99-overrides.ini'
            - './php-ini-overrides.ini:/etc/php/8.3/cli/conf.d/99-overrides.ini'
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - DB_CONNECTION=sqlite
            - DB_DATABASE=/application/app/database/db.db
